### ISSUE TITLE
Inconsistent naming: 'fragment' vs 'segment'

### ISSUE THREAD

**Issue by llugin** [pmem/vmemcache#110]
in libvmemcache.h:
VMEMcache *vmemcache_new(const char *path, size_t max_size, size_t **segment_size**,
enum vmemcache_replacement_policy replacement_policy);

However, in a macro variable for minimum segment size it's called fragment, not segment:
#define VMEMCACHE_MIN_FRAG ((size_t)8) /* minimum fragment size: 8B */

**Comment by pbalcer** [comment]
Let's adopt fs-like nomenclature and all this "extent".

**Comment by llugin** [comment]
verified on df56018cb45cc0b58f091ea02ee4e5d9cbd0a033
