### ISSUE TITLE
Is 'PMEM_MMAP_HINT' a proper name for an env used by vmemcache?

### ISSUE THREAD

**Issue by llugin** [pmem/vmemcache#157]
In src/mmap.c:73:

`char *e = os_getenv("PMEM_MMAP_HINT");`

Found on: 67bbf27c3854fdde45ef320804136c944c18e674

**Comment by ldorau** [comment]
This code is not used and it will not be used, so it should be removed - see #166

**Comment by ldorau** [comment]
@llugin there is no 'PMEM_MMAP_HINT' in the code now, please verify and close

**Comment by llugin** [comment]
Verified on d4e5468732b2989726b949af8f635fa06282663c
