### ISSUE TITLE
test-heap-usage fails with gcc-9

### ISSUE THREAD

**Issue by kilobyte** [pmem/vmemcache#192]
There's some 40 byte usable 32 byte real allocation that doesn't get freed.

Reproduces on gcc-9 on multiple machines, doesn't reproduce on gcc-8 nor clang.

**Comment by ldorau** [comment]
For reference see https://github.com/pmem/vmemcache/pull/191 and https://github.com/pmem/vmemcache/pull/191#issuecomment-477093265

**Comment by kilobyte** [comment]
That info is useless — the fail happened on my home machine (on which I tested the pull request in the morning before going to work) not because of a hardware specific (unlike a recent issue in PMDK) but because of gcc-9.

**Comment by ldorau** [comment]
It does NOT reproduce with:
gcc-9 (GCC) 9.0.1 20190411 (experimental) (commit 29659b5)
https://github.com/gcc-mirror/gcc/commit/29659b56ca23de6635b0efd28948e9ebaba3ec0b

**Comment by kilobyte** [comment]
Nor with:
gcc version 9.0.1 20190402 (experimental) [trunk revision 270074] (Debian 9-20190402-1)
Yay!
