### ISSUE TITLE
what's difference between VMEMCACHE_STAT_ENTRIE, VMEMCACHE_STAT_HEAP_ENTRIES and 	VMEMCACHE_STATS_NUM

### ISSUE THREAD

**Issue by ConeyLiu** [pmem/vmemcache#240]
Hi, what's difference between VMEMCACHE_STAT_ENTRIE, VMEMCACHE_STAT_HEAP_ENTRIES and 	VMEMCACHE_STATS_NUM ?

**Comment by kilobyte** [comment]
Good question — the documentation doesn't provide an adequate explanation, we need to fix that.

 * **VMEMCACHE_STAT_ENTRIES** is how many key:value pairs are in the cache; this is how many entries have been put but haven't been evicted yet
 * **VMEMCACHE_STAT_HEAP_ENTRIES** is merely a detail of internal allocator, a metric of free space fragmentation
 * **VMEMCACHE_STATS_NUM** is the number of statistics you can ask about

**Comment by ConeyLiu** [comment]
thanks a lot.
